I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ScriptAndCases/Intro/script_intro.rpy", line 35, in script
    "La balance trouve toujours, le bon côté ou pencher." with dissolve (0.3)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ScriptAndCases/Intro/script_intro.rpy", line 35, in script
    "La balance trouve toujours, le bon côté ou pencher." with dissolve (0.3)
  File "D:\truc\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\truc\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\truc\renpy-8.1.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\truc\renpy-8.1.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "D:\truc\renpy-8.1.3-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\truc\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\truc\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\truc\renpy-8.1.3-sdk\renpy\display\core.py", line 3976, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "D:\truc\renpy-8.1.3-sdk\renpy\display\core.py", line 3922, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Ace Attorney: Walter Romanng  Beta
Mon Nov 20 17:17:17 2023
