I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ScriptAndCases/Case_1/Case1script.rpy", line 98, in script
    K "Pas d’inquiétude,{w=0,1} j’ai de quoi renverser l’accusation !"
ValueError: could not convert string to float: '0,1'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ScriptAndCases/Case_1/Case1script.rpy", line 98, in script
    K "Pas d’inquiétude,{w=0,1} j’ai de quoi renverser l’accusation !"
  File "D:\truc\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\truc\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\truc\renpy-8.1.3-sdk\renpy\character.py", line 1347, in __call__
    dtt = DialogueTextTags(what)
  File "D:\truc\renpy-8.1.3-sdk\renpy\character.py", line 83, in __init__
    value = float(value)
ValueError: could not convert string to float: '0,1'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Ace Attorney: Walter Romanng  Beta
Mon Dec 25 11:47:28 2023
